---
- name: Clone dotfiles
  git: accept_hostkey=yes
       repo=git://github.com/junousia/dotfiles.git dest=/home/{{ target_user }}/.dotfiles

- name: Install dotfiles
  command: sh install.sh
  args:
    chdir: /home/{{ target_user }}/.dotfiles
    creates: /home/{{ target_user }}/.vim/bundle/neobundle.git

- name: Install Vim plugins
  command: /home/{{ target_user }}/.vim/bundle/neobundle.vim/bin/neoinstall
