# -*- mode: ruby -*-
# vi: set ft=ruby :
VAGRANTFILE_API_VERSION = "2"

Vagrant.configure(VAGRANTFILE_API_VERSION) do |config|
  config.vm.box = "ubuntu/trusty32"
  config.ssh.insert_key = false
  config.ssh.private_key_path = [File.expand_path('~/.vagrant.d/insecure_private_key'), File.expand_path('~/.ssh/id_rsa')]
  config.vm.define "mmgw32" do |dev32|
  end

  config.vm.hostname = "mmgw32"
  config.vm.box_check_update = true
  config.ssh.forward_agent = true

  config.vm.provision :shell do |shell|
      shell.inline = "touch $1 && chmod 0440 $1 && echo $2 > $1"
      shell.args = %q{/etc/sudoers.d/root_ssh_agent "Defaults    env_keep += \"SSH_AUTH_SOCK\""}
  end

  config.vm.provision "ansible" do |ansible|
    ansible.playbook = "../mmgw32.yml"
    ansible.extra_vars = {
      target_user: ENV['USER'],
    }
  end

  config.vm.provider "virtualbox" do |v|
    v.name = "mmgw32"
    v.memory = 4096
    v.cpus = 2
  end
end
