---
- name: Install packages
  hosts: all
  gather_facts: no
  remote_user: vagrant

  tasks:
  - name: Update APT cache
    apt: update_cache=yes
    sudo: yes

  - name: Install list of packages
    apt: pkg={{item}} state=installed
    with_items:
      - cmake
      - build-essential
      - git
      - vim
      - lttng-tools
      - liblttng-ust0
      - python-scapy
      - python-nose
      - libboost-serialization1.55.0
      - libboost-program-options1.55.0
      - rpm
      - python-pip
      - python-dev
      - gdb
      - zsh
      - python-glanceclient
      - python-heatclient
      - python-keystoneclient
      - python-neutronclient
      - python-novaclient
    sudo: yes

  - pip: name=posix_ipc
    sudo: yes

  - name: Create symlink for Boost libraries
    file: src=/usr/lib/x86_64-linux-gnu/libboost_serialization.so.1.55.0 dest=/usr/lib/x86_64-linux-gnu/libboost_serialization.so.1.53.0 state=link
    sudo: yes

  - name: Create symlink for Boost libraries
    file: src=/usr/lib/x86_64-linux-gnu/libboost_program_options.so.1.55.0 dest=/usr/lib/x86_64-linux-gnu/libboost_program_options.so.1.53.0 state=link
    sudo: yes

  - name: Allow tcpdump
    shell: echo 0 | tee /proc/sys/kernel/yama/ptrace_scope
    sudo: yes

- name: Create user {{ target_user }}
  hosts: all
  gather_facts: no
  remote_user: vagrant

  tasks:
  - name: Create user
    user: name={{ target_user }} generate_ssh_key=yes ssh_key_bits=2048 ssh_key_file=.ssh/id_rsa groups=vagrant shell=/usr/bin/zsh
    sudo: yes

  - name: Passwordless sudo
    lineinfile: dest=/etc/sudoers state=present regexp='^{{ target_user }}\=' line='{{ target_user }} ALL=(ALL) NOPASSWD:ALL' validate='visudo -cf %s'
    sudo: yes

  - name: Authorized keys for {{ target_user }}
    authorized_key: user={{ target_user }} key="{{ lookup('file', '~/.ssh/id_rsa.pub') }}"
    sudo: yes

  - name: Authorized keys for vagrant
    authorized_key: user=vagrant key="{{ lookup('file', '~/.ssh/id_rsa.pub') }}"
    sudo: yes

- name: Configure user {{ target_user }}
  hosts: all
  gather_facts: no
  remote_user: "{{ target_user }}"

  tasks:
  - name: Clone dotfiles
    git: accept_hostkey=yes
         repo=git://github.com/junousia/dotfiles.git dest=/home/{{ target_user }}/.dotfiles

  - name: Install dotfiles
    command: sh install.sh
    args:
      chdir: /home/{{ target_user }}/.dotfiles
      creates: /home/{{ target_user }}/.vim/bundle/neobundle.git

  - name: Install Vim plugins
    command: /home/{{ target_user }}/.vim/bundle/neobundle.vim/bin/neoinstall
